name: Deploy to Nightcurly private
on:
    push:
        branches:
            - main
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: connecting to the server with ssh
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  script: ./nightcurly_deploy.sh
